---
- hosts: 172.31.92.213
  become: yes
  tasks:
  - name: i want to excute linux commands
    command: hostname -f
    register: myresult
  - name: i want to display myresult
    debug:
     msg: "{{myresult}}"

