---
- hosts: 172.31.92.213
  become: yes
  tasks:
  - name: create a file
    file:
     path: /home/ubuntu/file1
     state: touch
  - name: create a folder
    file:
     path: /home/ubuntu/dir1
     state: directory
      