---
- hosts: 172.31.83.168
  become: yes
  tasks:
   - include_tasks: myfiles.yml
   - name: create a folder
     file:
       path: /home/ubuntu/myfolder
       state: directory
   - name: copy a file
     copy:
      src: staticfile
      dest: /home/ubuntu/mystaticfile.txt
      
