---
- hosts: all
  become: yes
  tasks:
  - name: ping all my nodes
    ping:
  - name: i want to install apache2
    apt:
     name: apache2
     state: present
  - name: install tree
    apt:
     name: tree
     state: present
     
