---
- hosts: 172.31.92.213
  become: yes
  tasks:
  - name: install tree
    apt:
     name: tree
     state: present
    tags: tree
  - name: install wget
    apt:
     name: wget
     state: present
    tags: wget
  - name: install git
    apt:
     name: git
     state: present
    tags: git
    
